version: '3.8'

services:
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: lms_app
    restart: unless-stopped
    working_dir: /var/www/html
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=base64:O/1jwZpBNh/eR7Xl7eLGgXpYVg0/jKKKKUNSLfCxSxE=
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=lms
      - DB_USERNAME=lmsuser
      - DB_PASSWORD=lmspass
      - CACHE_DRIVER=array
      - SESSION_DRIVER=array
    volumes:
      - /var/www/html/vendor
      - ./backend/app:/var/www/html/app
      - ./backend/routes:/var/www/html/routes
      - ./backend/config:/var/www/html/config
      - ./backend/database:/var/www/html/database
      - ./backend/tests:/var/www/html/tests
      - ./backend/public:/var/www/html/public
      - ./backend/storage/app/public:/var/www/html/storage/app/public
      - ./backend/storage/logs:/var/www/html/storage/logs
    depends_on:
      - db
    networks:
      - lms-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: lms_frontend
    restart: unless-stopped
    working_dir: /app
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://206.189.46.60/api
    networks:
      - lms-network

  db:
    image: mysql:8.0
    container_name: lms_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: lms
      MYSQL_USER: lmsuser
      MYSQL_PASSWORD: lmspass
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - lms-network

  nginx:
    image: nginx:stable
    container_name: lms_nginx
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./certs:/etc/letsencrypt
    depends_on:
      - frontend
      - app
    networks:
      - lms-network

volumes:
  db_data:
    driver: local

networks:
  lms-network:
    driver: bridge
